'use strict';

/**
 * blog-post router
 *
 * Default CRUD routes are auto-generated by Strapi.
 * This file only defines the default core router.
 */

const { createCoreRouter } = require('@strapi/strapi').factories;

module.exports = createCoreRouter('api::blog-post.blog-post');
